server:
  port: 8080

spring:
  application:
    name: minitoring-service 

management:
  endpoints:
    enabled-by-defaults: false
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    prometheus:
      enabled: true